package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class MainSceneController extends SetProperty implements Initializable {
	@FXML
	private Button ensureButton;
	@FXML
	private TextField numberTextField;
	@FXML
	private PasswordField passwordTextField;

	@FXML
	private ImageView ImageMain;
	private Image imgphone;

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		imgphone = new Image(getClass().getResource("/phone.jpg").toString(), ImageMain.getFitWidth(),
				ImageMain.getFitHeight(), true, true);
		ImageMain.setImage(imgphone);
	}

	// Event Listener on Button[#ensureButton].onAction
	@FXML
	public void OnClickEnsureButton(ActionEvent event) {
		// TODO Autogenerated
		String number = numberTextField.getText();
		String password = passwordTextField.getText();

		Statement statement = null;
		ResultSet resultSet = null;
		int type = 0;
		String sql = null;

		try {
			statement = connection.createStatement();
			sql = "SELECT * FROM employee WHERE employee.eno = '" + number + "' AND employee.`password` = '" + password
					+ "'";
			resultSet = statement.executeQuery(sql);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		boolean flag = false;
		try {
			while (resultSet.next()) {
				String truenumber = resultSet.getString(1);
				String truepassword = resultSet.getString(2);
				type = resultSet.getInt(3);
				if (truenumber.equals(number) && truepassword.equals(password)) {
					flag = true;
					break;
				}
			}
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		if (flag) {
			System.out.println("登录成功！");
			main.setEno(number);
			if (type == 1) {
				PurchaseSceneController purchaseSceneController = null;
				main.getStage().setTitle("进货人员操作");
				main.changeScene("PurchaseScene.fxml", purchaseSceneController, main);
			} else if (type == 2) {
				ShippingSceneController shippingSceneController = null;
				main.getStage().setTitle("出货人员操作");
				main.changeScene("ShippingScene.fxml", shippingSceneController, main);
			} else if (type == 3) {
				CheckSceneController checkSceneController = null;
				main.getStage().setTitle("审核人员操作");
				main.changeScene("CheckScene.fxml", checkSceneController, main);
			} else {
				JOptionPane.showMessageDialog(null, "用户类型不存在！", "error", JOptionPane.INFORMATION_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(null, "账号或密码错误！", "error", JOptionPane.INFORMATION_MESSAGE);
		}

		try {
			resultSet.close();
			statement.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
