-- 博文表增添
INSERT INTO MBLOG
VALUES(50, '新添加标题', 2, 2010, 5, 1, '新添加内容');

-- 博文表修改
UPDATE MBLOG
SET TITLE='修改后的标题', CONT='修改后的内容'
WHERE BID=50;

-- 博文表删除
DELETE FROM MBLOG
WHERE BID=50;

-- 新表FANS_3
CREATE TABLE FANS_3
SELECT *
FROM USERS
WHERE UID IN
(
	SELECT UID
	FROM FRIENDS
	WHERE UIDFLED = 3
);

-- 触发器实验
DROP TRIGGER IF EXISTS DenySelf;
DELIMITER $

CREATE TRIGGER DenySelf
BEFORE UPDATE ON THUMB
FOR EACH ROW
BEGIN
	IF(NEW.UID = (SELECT UID FROM MBLOG WHERE MBLOG.BID = NEW.BID))
	THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '警告：博文作者不能点赞自己博文';
	END IF;
END $

DELIMITER ;

DROP TRIGGER IF EXISTS DenySelf1;
DELIMITER $
CREATE TRIGGER DenySelf1
BEFORE INSERT ON THUMB
FOR EACH ROW
BEGIN
	IF(NEW.UID = (SELECT UID FROM MBLOG WHERE MBLOG.BID = NEW.BID))
	THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '警告：博文作者不能点赞自己博文';
	END IF;
END $

DELIMITER ;